### ISSUE TITLE
Thanks for writing this

### ISSUE THREAD

**Issue by tuchandra** [markshannon/pep622-critique#4]
Hi,

I'm not a Python core developer nor contributor at all, but I keep up with python-dev and was following the discussion on PEP 622 closely. I appreciate your write-up here.

Navigating the mailing list archives can be challenging, in particular because it's hard to remember what was discussed at what time, or who brought it up. I don't believe that this introduces new ideas that I haven't seen on the mailing list, but synthesizing all of the irregularities and gotchas into one place is still useful.

I particularly like the critique of the HTTP response example. Not being able to use named constants limits the utility of this in the place where I think it could otherwise be most helpful. The stdlib approaches are instructive, too.

One nit: under Alternative Approaches, you reference PEP 626, not 622.

Thanks for this. I have no real suggestions for you, just wanted to write a note of appreciation.

**Comment by davidhalter** [comment]
Same here. Thanks for writing this, I'm pretty unhappy with the current proposal and would like to see it rejected.

I'm a big fan of how match works in some functional languages (and Rust), but the current PEP is just useless.

**Comment by markshannon** [comment]
> Same here. Thanks for writing this, I'm pretty unhappy with the current proposal and would like to see it rejected.
> 
> I'm a big fan of how match works in some functional languages (and Rust), but the current PEP is just useless.

I'd encourage you to make your objections known on the python-dev mailing list. A more diverse range of opinions is always good.

**Comment by davidhalter** [comment]
I finally got around to writing a critique, took me ages. Sorry for that.
I still hope they reject the current proposal.

**Comment by mara004** [comment]
From me too, thank you for writing this. I really don't understand how come this PEP ended up accepted.
The inability to match against constants, the ambiguous use of the `|` operator, the special meaning of `_`, and the increased indentation depth are appalling, just to name a few things.

I find StackOverflow user Eric summarized it quite well:
> People have been asking for something like a switch case for 30 years. Now it finally gets implemented and you cant even match a number with constants [...]. Who cares about all the advanced pattern matching you can do with this if it fails for such a common and simple use case [...]? This honestly just blows my mind.
