### ISSUE TITLE
PEP 626 is referred to in multiple cases where the reference should be PEP 622 

### ISSUE THREAD

**Issue by metaperl** [markshannon/pep622-critique#6]
# typo?
https://github.com/markshannon/pep622-critique#django-example

> The version of this example given in PEP 626 is as follows:

Why is he referring to [his own PEP 626](https://www.python.org/dev/peps/pep-0626/) which does not have such code?

# another typo?

https://github.com/markshannon/pep622-critique#is_tuple-example

> PEP 626 shows this example rewritten as:

626????

# third typo?

https://github.com/markshannon/pep622-critique#http-response-example

> PEP 626 prevents the use of simple symbolic constants, so the statement cannot be written as

> PEP 626 does not prohibit the above syntax. 

# 4th typo?

https://github.com/markshannon/pep622-critique#analysis-of-the-potential-usefulness-of-pep-626

Right in the title of the section...

**Comment by markshannon** [comment]
fixed
